<a href="https://colab.research.google.com/github/Theanh130124/DataMining_Colab/blob/main/BaiThucHanhNhom_Tuan6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CÂU 1: CHUẨN BỊ MÔI TRƯỜNG

In [1]:
# Import các thư viện cần thiết
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import shuffle

# Tải dữ liệu từ file optdigits.csv
data = pd.read_csv('/content/optdigits.csv')  # Cập nhật đường dẫn nếu cần




# Tách dữ liệu thành X (features) và y (target label)
X = data.iloc[:, :-1]  # Tất cả cột trừ cột cuối (features)
y = data.iloc[:, -1]   # Cột cuối cùng (label)

# Bảo đảm dữ liệu ngẫu nhiên
X, y = shuffle(X, y, random_state=42)

In [2]:
# Hiển thị 5 dòng dữ liệu đầu tiên
print("Dữ liệu ban đầu:")
print(data.head())

Dữ liệu ban đầu:
   input1  input2  input3  input4  input5  input6  input7  input8  input9  \
0       0       1       6      15      12       1       0       0       0   
1       0       0      10      16       6       0       0       0       0   
2       0       0       8      15      16      13       0       0       0   
3       0       0       0       3      11      16       0       0       0   
4       0       0       5      14       4       0       0       0       0   

   input10  ...  input56  input57  input58  input59  input60  input61  \
0        7  ...        0        0        0        6       14        7   
1        7  ...        0        0        0       10       16       15   
2        1  ...        0        0        0        9       14        0   
3        0  ...        0        0        0        0        1       15   
4        0  ...        0        0        0        4       12       14   

   input62  input63  input64  class  
0        1        0        0      0  
1    

In [3]:
# Kiểm tra các thông tin cơ bản về dữ liệu
print("\nThông tin về dữ liệu:")
print(data.info())


Thông tin về dữ liệu:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5620 entries, 0 to 5619
Data columns (total 65 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   input1   5620 non-null   int64
 1   input2   5620 non-null   int64
 2   input3   5620 non-null   int64
 3   input4   5620 non-null   int64
 4   input5   5620 non-null   int64
 5   input6   5620 non-null   int64
 6   input7   5620 non-null   int64
 7   input8   5620 non-null   int64
 8   input9   5620 non-null   int64
 9   input10  5620 non-null   int64
 10  input11  5620 non-null   int64
 11  input12  5620 non-null   int64
 12  input13  5620 non-null   int64
 13  input14  5620 non-null   int64
 14  input15  5620 non-null   int64
 15  input16  5620 non-null   int64
 16  input17  5620 non-null   int64
 17  input18  5620 non-null   int64
 18  input19  5620 non-null   int64
 19  input20  5620 non-null   int64
 20  input21  5620 non-null   int64
 21  input22  5620 non-null   int64
 22  i

In [4]:
# Tách dữ liệu thành X (features) và y (target label)
X = data.iloc[:, :-1]  # Tất cả cột trừ cột cuối (features)
y = data.iloc[:, -1]   # Cột cuối cùng (label)

# Bảo đảm dữ liệu ngẫu nhiên
X, y = shuffle(X, y, random_state=42)

a) Test bằng % split và k-cross validation (k=10)

In [5]:
# Chia dữ liệu thành tập huấn luyện và tập kiểm tra theo tỉ lệ 70/30
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

# Tạo mô hình Cây Quyết Định
dtree = DecisionTreeClassifier(random_state=42)

# Phương pháp 1: % split
print("\nKết quả với phương pháp % split:")
dtree.fit(X_train, y_train)
y_pred = dtree.predict(X_test)

# Đánh giá mô hình
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

# Phương pháp 2: K-Fold Cross Validation (k=10)
print("\nKết quả với phương pháp k-cross validation (k=10):")
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
cv_scores = cross_val_score(dtree, X, y, cv=cv, scoring='accuracy')

print(f"Độ chính xác trung bình: {np.mean(cv_scores):.4f}")
print(f"Độ lệch chuẩn: {np.std(cv_scores):.4f}")


Kết quả với phương pháp % split:
Confusion Matrix:
[[162   0   0   0   0   0   0   1   3   0]
 [  0 143   5   1   1   5   3   2   2   9]
 [  0   2 158   0   1   0   2   1   3   0]
 [  0   4   2 155   0   3   0   0   3   5]
 [  4   2   0   0 144   3   9   1   2   6]
 [  3   5   1   2   5 139   0   1   4   7]
 [  0   2   1   0   0   1 163   0   0   0]
 [  0   0   3   0   2   0   0 163   1   1]
 [  2  14   2   1   3   4   1   1 134   4]
 [  1   2   1   5   1   1   0   3   4 151]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.98      0.96       166
           1       0.82      0.84      0.83       171
           2       0.91      0.95      0.93       167
           3       0.95      0.90      0.92       172
           4       0.92      0.84      0.88       171
           5       0.89      0.83      0.86       167
           6       0.92      0.98      0.94       167
           7       0.94      0.96      0.95       170
       

So sánh: Nếu độ chính xác trung bình của K-Fold cao hơn, chứng tỏ mô hình ổn định hơn so với % split. (Accuracy)

So sánh: Phương pháp nào có độ lệch chuẩn nhỏ hơn thì mô hình đáng tin cậy hơn.
So sánh: Nếu Confusion Matrix và các chỉ số như Precision, Recall, F1-Score của % split chấp nhận được và tương đương kết quả k-fold, có thể chọn phương pháp này để tiết kiệm thời gian.

Nếu thời gian không phải là vấn đề, K-Fold Cross Validation thường được xem là tốt hơn vì nó cung cấp đánh giá toàn diện và ổn định hơn.
Nếu muốn đánh giá nhanh hoặc khi dữ liệu rất lớn, % Split có thể đủ để kiểm tra mô hình.


In [6]:
#b)
# Chia dữ liệu thành TrainData và TestData
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify=y, random_state=42)

# Lưu TrainData và TestData ra file
train_data = pd.concat([X_train, y_train], axis=1)
test_data = pd.concat([X_test, y_test], axis=1)

train_data.to_csv('TrainData.csv', index=False)
test_data.to_csv('TestData.csv', index=False)

print("\nTrainData và TestData đã được lưu thành công.")



TrainData và TestData đã được lưu thành công.


In [7]:
# Huấn luyện lại mô hình với TrainData
dtree.fit(X_train, y_train)
y_pred_test = dtree.predict(X_test)
#c)
# Đánh giá mô hình trên TestData
print("\nKết quả trên TestData:")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_test))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_test))
print("\nAccuracy:", accuracy_score(y_test, y_pred_test))



Kết quả trên TestData:

Confusion Matrix:
[[55  0  0  0  0  0  0  0  0  0]
 [ 0 51  1  1  0  1  0  0  2  1]
 [ 0  1 52  2  0  0  0  0  1  0]
 [ 0  0  2 53  0  1  0  0  1  0]
 [ 0  1  0  0 52  1  1  0  1  1]
 [ 0  0  0  0  0 55  0  0  1  0]
 [ 0  0  0  0  0  1 55  0  0  0]
 [ 0  1  0  0  0  0  0 54  1  1]
 [ 0  2  1  4  3  0  1  0 43  1]
 [ 0  1  0  0  2  1  0  0  0 52]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        55
           1       0.89      0.89      0.89        57
           2       0.93      0.93      0.93        56
           3       0.88      0.93      0.91        57
           4       0.91      0.91      0.91        57
           5       0.92      0.98      0.95        56
           6       0.96      0.98      0.97        56
           7       1.00      0.95      0.97        57
           8       0.86      0.78      0.82        55
           9       0.93      0.93      0.93        56

    ac

In [ ]:
#Câu 2
# Tạo mô hình Naïve Bayes
nb_model = GaussianNB()

# Huấn luyện với TrainData
nb_model.fit(X_train, y_train)

# Dự đoán trên TestData
y_pred_nb = nb_model.predict(X_test)

# Đánh giá kết quả
print(\"\\nKết quả của Naïve Bayes trên TestData:\")
print(\"Confusion Matrix:\")
print(confusion_matrix(y_test, y_pred_nb))
print(\"Classification Report:\")
print(classification_report(y_test, y_pred_nb))
print(\"Accuracy:\", accuracy_score(y_test, y_pred_nb))


In [ ]:
print(\"\\nSo sánh kết quả giữa Cây Quyết Định và Naïve Bayes:\")
accuracy_dtree = accuracy_score(y_test, y_pred_test)
accuracy_nb = accuracy_score(y_test, y_pred_nb)

print(f\"Accuracy của Cây Quyết Định: {accuracy_dtree:.4f}\")
print(f\"Accuracy của Naïve Bayes: {accuracy_nb:.4f}\")

if accuracy_dtree > accuracy_nb:
    print(\"=> Cây Quyết Định cho kết quả tốt hơn.\")
else:
    print(\"=> Naïve Bayes cho kết quả tốt hơn.\")
